name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  packages: write
  contents: read

jobs:
  lint-build:
    env:
      VERSION: latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.21.x"

      - name: Run linter
        uses: golangci/golangci-lint-action@v3

      - name: Build container image
        run: make image

      - name: Push container image
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u THIS_DOES_NOT_MATTER --password-stdin
          make image-push
