name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
      - name: Build the Docker image
        run: docker build . --file build/Dockerfile --tag benc-uk/htmx-go-todo:$(date +%s)
